package fhtml

type ElemCSS struct {
	Other map[string]string

	AlignContent             *string
	AnimationFillMode        *string
	AnimationIterationCount  *string
	AnimationName            *string
	AnimationPlayState       *string
	AnimationTimingFunction  *string
	BackfaceVisibility       *string
	Background               *string
	BackgroundAttachment     *string
	BackgroundBlendMode      *string
	BackgroundClip           *string
	BackgroundColor          *string
	BackgroundImage          *string
	BackgroundOrigin         *string
	BackgroundPosition       *string
	BackgroundRepeat         *string
	BackgroundSize           *string
	Border                   *string
	BorderBottom             *string
	BorderBottomColor        *string
	BorderBottomLeftRadius   *string
	BorderBottomRightRadius  *string
	BorderBottomStyle        *string
	BorderBottomWidth        *string
	BorderCollapse           *string
	BorderColor              *string
	BorderImage              *string
	BorderImageOutset        *string
	BorderImageRepeat        *string
	BorderImageSlice         *string
	BorderImageSource        *string
	BorderImageWidth         *string
	BorderLeft               *string
	BorderLeftColor          *string
	BorderLeftStyle          *string
	BorderLeftWidth          *string
	BorderRadius             *string
	BorderRight              *string
	BorderRightColor         *string
	BorderRightStyle         *string
	BorderRightWidth         *string
	BorderSpacing            *string
	BorderStyle              *string
	BorderTop                *string
	BorderTopColor           *string
	BorderTopLeftRadius      *string
	BorderTopRightRadius     *string
	BorderTopStyle           *string
	BorderTopWidth           *string
	BorderWidth              *string
	Bottom                   *string
	BoxShadow                *string
	BoxSizing                *string
	CaptionSide              *string
	CaretColor               *string
	Atcharset                *string
	Clear                    *string
	Clip                     *string
	ClipPath                 *string
	Color                    *string
	ColumnCount              *string
	ColumnFill               *string
	ColumnGap                *string
	ColumnRule               *string
	ColumnRuleColor          *string
	ColumnRuleStyle          *string
	ColumnRuleWidth          *string
	ColumnSpan               *string
	ColumnWidth              *string
	Columns                  *string
	Content                  *string
	CounterIncrement         *string
	CounterReset             *string
	Cursor                   *string
	Direction                *string
	Display                  *string
	EmptyCells               *string
	Filter                   *string
	Flex                     *string
	FlexBasis                *string
	FlexDirection            *string
	FlexFlow                 *string
	FlexGrow                 *string
	FlexShrink               *string
	FlexWrap                 *string
	Float                    *string
	Font                     *string
	AtfontFace               *string
	FontFamily               *string
	FontKerning              *string
	FontSize                 *string
	FontSizeAdjust           *string
	FontStretch              *string
	FontStyle                *string
	FontVariant              *string
	FontWeight               *string
	Grid                     *string
	GridArea                 *string
	GridAutoColumns          *string
	GridAutoFlow             *string
	GridAutoRows             *string
	GridColumn               *string
	GridColumnEnd            *string
	GridColumnGap            *string
	GridColumnStart          *string
	GridGap                  *string
	GridRow                  *string
	GridRowEnd               *string
	GridRowGap               *string
	GridRowStart             *string
	GridTemplate             *string
	GridTemplateAreas        *string
	GridTemplateColumns      *string
	GridTemplateRows         *string
	Height                   *string
	Hyphens                  *string
	Atimport                 *string
	JustifyContent           *string
	Atkeyframes              *string
	Left                     *string
	LetterSpacing            *string
	LineHeight               *string
	ListStyle                *string
	ListStyleImage           *string
	ListStylePosition        *string
	ListStyleType            *string
	Margin                   *string
	MarginBottom             *string
	MarginLeft               *string
	MarginRight              *string
	MarginTop                *string
	MaxHeight                *string
	MaxWidth                 *string
	Atmedia                  *string
	MinHeight                *string
	MinWidth                 *string
	ObjectFit                *string
	ObjectPosition           *string
	Opacity                  *string
	Order                    *string
	Outline                  *string
	OutlineColor             *string
	OutlineOffset            *string
	OutlineStyle             *string
	OutlineWidth             *string
	Overflow                 *string
	OverflowX                *string
	OverflowY                *string
	Padding                  *string
	PaddingBottom            *string
	PaddingLeft              *string
	PaddingRight             *string
	PaddingTop               *string
	PageBreakAfter           *string
	PageBreakBefore          *string
	PageBreakInside          *string
	Perspective              *string
	PerspectiveOrigin        *string
	PointerEvents            *string
	Position                 *string
	Quotes                   *string
	Right                    *string
	ScrollBehavior           *string
	TableLayout              *string
	TextAlign                *string
	TextAlignLast            *string
	TextDecoration           *string
	TextDecorationColor      *string
	TextDecorationLine       *string
	TextDecorationStyle      *string
	TextIndent               *string
	TextJustify              *string
	TextOverflow             *string
	TextShadow               *string
	TextTransform            *string
	Top                      *string
	Transform                *string
	TransformOrigin          *string
	TransformStyle           *string
	Transition               *string
	TransitionDelay          *string
	TransitionDuration       *string
	TransitionProperty       *string
	TransitionTimingFunction *string
	UserSelect               *string
	VerticalAlign            *string
	Visibility               *string
	WhiteSpace               *string
	Width                    *string
	WordBreak                *string
	WordSpacing              *string
	WordWrap                 *string
	WritingMode              *string
	ZIndex                   *string
}
